Repository alan-turing-institute/scivision, pull requests merged in 2021-08, with the labels that each got.

#30 add koala logging
  examples/query_scivision_catalog.ipynb
  scivision/.DS_Store
  scivision/__init__.py
  scivision/catalog/catalog.py
  scivision/io/reader.py
  scivision/koala.py
  tests/test_koala.py
Labels: enhancement, feature

#46 try to fix notebook -
  dev/README.md
  examples/demo_endtoend_imagenet.ipynb
  pretrained_imagenet_scivision_example.ipynb
Labels: bug

#47 setup.py file request
  environment.yml
  requirements.txt
  setup.py
Labels: feature

#44 Update github workflow to include pytest
  .github/workflows/scivision.yml
Labels: enhancement

#50 Add readthedocs base layout
  docs/Makefile
  docs/_static/ati_logo.png
  docs/api.rst
  docs/conf.py
  docs/how_to_install.md
  docs/index.rst
  docs/make.bat
Labels: documentation

#51 Add install instructions to readme
  README.md
Labels: documentation
